apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: model-serving
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 30000
      name: metrics
      protocol: TCP
      targetPort: 8000 # This is the port that the application is listening on (pod)
  type: LoadBalancer
