apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: model-serving
spec:
  replicas: 1  # Set to 3 for production
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: logs
              mountPath: /var/log/container
      volumes:
        - name: logs
          emptyDir: {}  # Changed to emptyDir for temporary storage 